"""Intervention evidence system (spec v04 §7, §8, §13, §15).

Three propositions are stored and rendered separately and none inherits the
truth of another (§15.7):

1. ``evidence_signal_associated_with_state`` — the disease profiles and the
   species interpretation registry hold this;
2. ``evidence_intervention_changes_signal`` — a microbiome-surrogate outcome;
3. ``evidence_intervention_changes_clinical_outcome`` — a patient outcome.

The registry lives in ``interventions/*.yaml``: exact intervention
identities, studied protocols, PICO evidence assertions (positive, null,
harm and guideline records alike), safety rules (compiled by
:mod:`openbiota.safety`) and compiled *action mappings* that join a trigger
selector to a protocol, its evidence, its counter-evidence, its safety rules
and its confirmation requirements.

The engine (:func:`generate`) follows the §7.7 algorithm: typed triggers
from QC-qualified findings → exact-key binding → population/indication/
confirmation checks → every safety rule → lane + applicability →
transparent, non-ranked output, with ``no_supported_targeted_intervention``
as a first-class successful result. Nothing here computes a treatment score
or a probability of benefit, and no production sentence is generated by a
language model: prose is assembled deterministically from approved records.
"""

from __future__ import annotations

import fnmatch
import hashlib
import json
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Final

import yaml

from openbiota.errors import OpenBiotaError
from openbiota.safety import (
    INTERVENTION_CLASSES,
    SafetyRule,
    SafetyVerdict,
    apply_rules,
    compile_rule,
    participant_safety_sentence,
)

REGISTRY_VERSION: Final = "interventions_v04.1"

LANES: Final = ("A", "B", "C", "D", "E", "X")
LANE_MEANING: Final = {
    "A": "current authoritative guideline or regulatory label for an independently confirmed indication",
    "B": "replicated human randomized clinical benefit for the exact intervention and population",
    "C": "single, pilot or conflicting human randomized evidence (clinical or surrogate endpoint)",
    "D": "non-randomized human, pilot, case-series or observational evidence",
    "E": "animal, in-vitro or mechanistic evidence only",
    "X": "against-evidence record: guideline against, null or conflicting evidence, or harm signal",
    "none": "no supporting evidence lane",
}
AGAINST_ORDER: Final = ("guideline_against", "null_primary", "harm_signal", "conflicting")
GUIDELINE_POSITIONS: Final = (
    "strong_for", "conditional_for", "no_recommendation", "trial_only",
    "conditional_against", "strong_against", "unavailable",
)
OUTCOME_CLASSES: Final = ("patient_clinical", "patient_reported", "validated_biomarker", "microbiome_surrogate", "mechanistic")
SOURCE_TYPES: Final = (
    "randomized_trial", "nonrandomized_study", "observational_study", "case_report", "systematic_review",
    "meta_analysis", "guideline", "regulatory_label", "regulatory_safety_communication", "protocol", "preprint",
    "consensus_statement", "reference_fact_sheet",
)
TRIGGER_TYPES: Final = (
    "clinician_confirmed_condition", "symptom_phenotype", "external_lab_abnormality",
    "exact_microbiome_feature", "functional_capacity_finding", "ecological_finding",
    "research_profile_resemblance",
)
RENDERS: Final = (
    "not_actionable", "inform_only", "evidence_only", "clinician_review",
    "guideline_route_after_confirmation", "no_supported_targeted_intervention",
)
PROPOSITIONS: Final = (
    "evidence_signal_associated_with_state",
    "evidence_intervention_changes_signal",
    "evidence_intervention_changes_clinical_outcome",
)

PRESCRIPTION_SENTENCE: Final = (
    "This is a clinician-review evidence route, not a recommendation generated from the microbiome result."
)
FMT_STATUS_SENTENCE: Final = (
    "Outside recurrent C. difficile infection, fecal microbiota transplantation is investigational: it may be "
    "studied only in a specific clinical investigation under an effective IND with IRB oversight and informed "
    "consent, unless FDA has determined an IND is not required. A favourable paper, guideline or trial "
    "registration does not authorise treatment."
)
NO_TARGETED_SENTENCE: Final = (
    "No supported targeted intervention was found in registry version {version} for this finding. "
    "That is a result, not a gap in the analysis: it means no human study has shown that changing this "
    "reading changes a health outcome."
)


# --------------------------------------------------------------------------- #
# registry records
# --------------------------------------------------------------------------- #


@dataclass(frozen=True, slots=True)
class Intervention:
    intervention_id: str
    version: str
    intervention_class: str
    display_name: str
    identity: dict[str, Any]
    transfer_policy: dict[str, str]
    exact_protocol_reproducibility: str      # complete | incomplete
    regulatory_status: str | None = None
    label_warnings: tuple[str, ...] = ()


@dataclass(frozen=True, slots=True)
class Protocol:
    protocol_id: str
    intervention_id: str
    population: dict[str, Any]
    administration: dict[str, Any]
    studied_protocol_not_personalized_instruction: bool = True

    @property
    def dose_text(self) -> str:
        return str(self.administration.get("dose_source_text") or "dose as studied (see source)")


@dataclass(frozen=True, slots=True)
class Assertion:
    evidence_assertion_id: str
    protocol_ref: str | None
    intervention_ref: str | None
    source: dict[str, Any]
    study: dict[str, Any]
    pico: dict[str, Any]
    lane: str                                # A–E or X
    proposition: str
    against_kind: str | None                 # for lane X: guideline_against | null_primary | harm_signal | conflicting
    target_binding: dict[str, Any]
    summary: str
    guideline_position: str = "unavailable"

    @property
    def effect_direction(self) -> str:
        return str(self.pico.get("effect", {}).get("direction") or "not_estimable")

    @property
    def outcome_class(self) -> str:
        return str(self.pico.get("outcome", {}).get("class") or "mechanistic")

    @property
    def url(self) -> str:
        s = self.source
        if s.get("url"):
            return str(s["url"])
        if s.get("pmid"):
            return f"https://pubmed.ncbi.nlm.nih.gov/{s['pmid']}/"
        if s.get("doi"):
            return f"https://doi.org/{s['doi']}"
        return ""

    @property
    def citation(self) -> str:
        return str(self.source.get("citation") or self.url)


@dataclass(frozen=True, slots=True)
class TriggerSelector:
    trigger_type: str
    target: str                   # profile name / panel name / group name / species / condition / symptom
    direction: str = "any"        # high | low | present | any
    min_level: str | None = None  # for percentile-based triggers: e.g. "elevated" or "notably_high"

    def patterns(self) -> tuple[str, ...]:
        """``{a,b_*}`` alternation on top of fnmatch wildcards."""
        t = self.target.strip()
        if t.startswith("{") and t.endswith("}"):
            return tuple(p.strip() for p in t[1:-1].split(",") if p.strip())
        return (t,)

    def matches(self, trigger: TriggerRecord) -> bool:
        if trigger.trigger_type != self.trigger_type:
            return False
        if not any(fnmatch.fnmatchcase(trigger.target, p) for p in self.patterns()):
            return False
        if self.direction != "any" and trigger.direction != self.direction:
            return False
        if self.min_level is not None and trigger.level_rank is not None:
            return trigger.level_rank >= LEVEL_RANK.get(self.min_level, 0)
        return True


@dataclass(frozen=True, slots=True)
class ActionMapping:
    action_mapping_id: str
    trigger_selector: TriggerSelector
    render: str
    intervention_protocol_ref: str | None
    evidence_assertion_refs: tuple[str, ...]
    against_evidence_assertion_refs: tuple[str, ...]
    safety_rule_refs: tuple[str, ...]
    confirmation_rule_refs: tuple[str, ...]      # conditions that must be clinician-confirmed
    participant_claim_release_ref: str | None
    title: str
    context_note: str
    never_say: tuple[str, ...]
    sources: tuple[dict[str, str], ...]
    follow_up_route: str | None = None
    fmt_status: str | None = None


LEVEL_RANK: Final = {
    "notably_low": -3, "low": -2, "somewhat_low": -1, "typical": 0,
    "somewhat_high": 1, "high": 2, "notably_high": 3, "elevated": 2, "reduced": -2,
}


@dataclass(slots=True)
class Registry:
    version: str
    interventions: dict[str, Intervention]
    protocols: dict[str, Protocol]
    assertions: dict[str, Assertion]
    safety_rules: dict[str, SafetyRule]
    mappings: list[ActionMapping]
    digest: str

    def validate(self) -> list[str]:
        problems: list[str] = []
        for p in self.protocols.values():
            if p.intervention_id not in self.interventions:
                problems.append(f"protocol {p.protocol_id} references unknown intervention {p.intervention_id}")
        for a in self.assertions.values():
            if a.protocol_ref and a.protocol_ref not in self.protocols:
                problems.append(f"assertion {a.evidence_assertion_id} references unknown protocol {a.protocol_ref}")
            if a.intervention_ref and a.intervention_ref not in self.interventions:
                problems.append(f"assertion {a.evidence_assertion_id} references unknown intervention {a.intervention_ref}")
            if a.lane not in LANES:
                problems.append(f"assertion {a.evidence_assertion_id} has lane {a.lane!r}")
            if a.lane == "X" and a.against_kind not in AGAINST_ORDER:
                problems.append(f"assertion {a.evidence_assertion_id} is lane X without a valid against_kind")
            if a.lane != "X" and a.against_kind:
                problems.append(f"assertion {a.evidence_assertion_id} has against_kind but lane {a.lane}")
            if a.proposition not in PROPOSITIONS:
                problems.append(f"assertion {a.evidence_assertion_id} proposition {a.proposition!r}")
            if a.source.get("source_type") not in SOURCE_TYPES:
                problems.append(f"assertion {a.evidence_assertion_id} source_type {a.source.get('source_type')!r}")
            if not (a.source.get("pmid") or a.source.get("doi") or a.source.get("url")):
                problems.append(f"assertion {a.evidence_assertion_id} has no PMID, DOI or URL")
            if a.outcome_class not in OUTCOME_CLASSES:
                problems.append(f"assertion {a.evidence_assertion_id} outcome class {a.outcome_class!r}")
            if a.guideline_position not in GUIDELINE_POSITIONS:
                problems.append(f"assertion {a.evidence_assertion_id} guideline_position {a.guideline_position!r}")
        seen: set[str] = set()
        for m in self.mappings:
            if m.action_mapping_id in seen:
                problems.append(f"duplicate action_mapping_id {m.action_mapping_id}")
            seen.add(m.action_mapping_id)
            if m.render not in RENDERS:
                problems.append(f"mapping {m.action_mapping_id} render {m.render!r}")
            if m.trigger_selector.trigger_type not in TRIGGER_TYPES:
                problems.append(f"mapping {m.action_mapping_id} trigger_type {m.trigger_selector.trigger_type!r}")
            if m.intervention_protocol_ref and m.intervention_protocol_ref not in self.protocols:
                problems.append(f"mapping {m.action_mapping_id} references unknown protocol {m.intervention_protocol_ref}")
            for ref in m.evidence_assertion_refs + m.against_evidence_assertion_refs:
                if ref not in self.assertions:
                    problems.append(f"mapping {m.action_mapping_id} references unknown assertion {ref}")
            for ref in m.against_evidence_assertion_refs:
                if ref in self.assertions and self.assertions[ref].lane != "X":
                    problems.append(f"mapping {m.action_mapping_id}: against-evidence {ref} is not lane X")
            for ref in m.evidence_assertion_refs:
                if ref in self.assertions and self.assertions[ref].lane == "X":
                    problems.append(f"mapping {m.action_mapping_id}: supporting ref {ref} is lane X")
            for ref in m.safety_rule_refs:
                if ref not in self.safety_rules:
                    problems.append(f"mapping {m.action_mapping_id} references unknown safety rule {ref}")
            if m.intervention_protocol_ref:
                iv = self.interventions[self.protocols[m.intervention_protocol_ref].intervention_id]
                if iv.intervention_class in ("prescription_drug", "fmt_microbiota_product") and m.render not in (
                    "clinician_review", "guideline_route_after_confirmation", "evidence_only",
                ):
                    problems.append(f"mapping {m.action_mapping_id}: prescription/FMT must be clinician-review or evidence-only")
                if iv.intervention_class in ("prescription_drug", "fmt_microbiota_product") and not m.confirmation_rule_refs:
                    problems.append(f"mapping {m.action_mapping_id}: prescription/FMT needs a confirmation rule")
        return problems

    def to_lock(self) -> dict[str, Any]:
        return {
            "registry_version": self.version, "digest": self.digest,
            "interventions": len(self.interventions), "protocols": len(self.protocols),
            "assertions": len(self.assertions), "safety_rules": len(self.safety_rules),
            "action_mappings": len(self.mappings),
        }


def _as_tuple(value: Any) -> tuple[str, ...]:
    if value is None:
        return ()
    if isinstance(value, str):
        return (value,)
    return tuple(str(v) for v in value)


def load_registry(directory: Path) -> Registry:
    """Load and validate every YAML file under ``interventions/``."""
    files = sorted(directory.glob("*.yaml"))
    if not files:
        raise OpenBiotaError(f"no intervention registry under {directory}")
    raw: dict[str, list[Any]] = {"interventions": [], "protocols": [], "assertions": [], "safety_rules": [], "action_mappings": []}
    digest = hashlib.sha256()
    for path in files:
        text = path.read_text()
        digest.update(path.name.encode() + text.encode())
        data = yaml.safe_load(text) or {}
        for key in raw:
            raw[key].extend(data.get(key, []) or [])

    interventions: dict[str, Intervention] = {}
    for r in raw["interventions"]:
        cls = r.get("class")
        if cls not in INTERVENTION_CLASSES:
            raise OpenBiotaError(f"intervention {r.get('intervention_id')}: unknown class {cls!r}")
        iv = Intervention(
            intervention_id=r["intervention_id"], version=str(r.get("version", "1.0.0")), intervention_class=cls,
            display_name=r["display_name"], identity=dict(r.get("identity") or {}),
            transfer_policy=dict(r.get("transfer_policy") or {}),
            exact_protocol_reproducibility=str(r.get("exact_protocol_reproducibility", "complete")),
            regulatory_status=r.get("regulatory_status"), label_warnings=_as_tuple(r.get("label_warnings")),
        )
        if iv.intervention_id in interventions:
            raise OpenBiotaError(f"duplicate intervention_id {iv.intervention_id}")
        interventions[iv.intervention_id] = iv

    protocols: dict[str, Protocol] = {}
    for r in raw["protocols"]:
        p = Protocol(
            protocol_id=r["protocol_id"], intervention_id=r["intervention_id"],
            population=dict(r.get("population") or {}), administration=dict(r.get("administration") or {}),
        )
        if p.protocol_id in protocols:
            raise OpenBiotaError(f"duplicate protocol_id {p.protocol_id}")
        protocols[p.protocol_id] = p

    assertions: dict[str, Assertion] = {}
    for r in raw["assertions"]:
        a = Assertion(
            evidence_assertion_id=r["evidence_assertion_id"], protocol_ref=r.get("protocol_ref"),
            intervention_ref=r.get("intervention_ref"), source=dict(r.get("source") or {}),
            study=dict(r.get("study") or {}), pico=dict(r.get("pico") or {}), lane=str(r.get("lane", "")),
            proposition=str(r.get("proposition", "")), against_kind=r.get("against_kind"),
            target_binding=dict(r.get("target_binding") or {}), summary=str(r.get("summary", "")).strip(),
            guideline_position=str(r.get("guideline_position", "unavailable")),
        )
        if a.evidence_assertion_id in assertions:
            raise OpenBiotaError(f"duplicate evidence_assertion_id {a.evidence_assertion_id}")
        assertions[a.evidence_assertion_id] = a

    rules = {r.rule_id: r for r in (compile_rule(x) for x in raw["safety_rules"])}

    mappings: list[ActionMapping] = []
    for r in raw["action_mappings"]:
        sel = r.get("trigger_selector") or {}
        mappings.append(
            ActionMapping(
                action_mapping_id=r["action_mapping_id"],
                trigger_selector=TriggerSelector(
                    trigger_type=sel.get("trigger_type", ""), target=str(sel.get("target", "*")),
                    direction=str(sel.get("direction", "any")), min_level=sel.get("min_level"),
                ),
                render=str(r.get("render", "evidence_only")),
                intervention_protocol_ref=r.get("intervention_protocol_ref"),
                evidence_assertion_refs=_as_tuple(r.get("evidence_assertion_refs")),
                against_evidence_assertion_refs=_as_tuple(r.get("against_evidence_assertion_refs")),
                safety_rule_refs=_as_tuple(r.get("safety_rule_refs")),
                confirmation_rule_refs=_as_tuple(r.get("confirmation_rule_refs")),
                participant_claim_release_ref=r.get("participant_claim_release_ref"),
                title=str(r.get("title", "")), context_note=str(r.get("context_note", "")).strip(),
                never_say=_as_tuple(r.get("never_say")), sources=tuple(dict(s) for s in r.get("sources", []) or []),
                follow_up_route=r.get("follow_up_route"), fmt_status=r.get("fmt_status"),
            )
        )
    reg = Registry(
        version=REGISTRY_VERSION, interventions=interventions, protocols=protocols, assertions=assertions,
        safety_rules=rules, mappings=mappings, digest="sha256:" + digest.hexdigest(),
    )
    problems = reg.validate()
    if problems:
        raise OpenBiotaError("intervention registry invalid:\n  " + "\n  ".join(problems))
    return reg


# --------------------------------------------------------------------------- #
# triggers
# --------------------------------------------------------------------------- #


@dataclass(frozen=True, slots=True)
class TriggerRecord:
    trigger_id: str
    trigger_type: str
    target: str
    direction: str                    # high | low | present | any
    source_record_ref: str
    confirmation_status: str          # verified | self_reported | profile_only | unknown
    level: str | None = None
    level_rank: int | None = None
    microbial_context: dict[str, Any] | None = None
    display: str = ""

    def to_json(self) -> dict[str, Any]:
        return {
            "trigger_id": self.trigger_id, "trigger_type": self.trigger_type, "target": self.target,
            "direction": self.direction, "source_record_ref": self.source_record_ref,
            "confirmation_status": self.confirmation_status, "level": self.level,
            "microbial_context": self.microbial_context, "display": self.display,
        }


def _rank(level: str | None) -> int | None:
    if level is None:
        return None
    return LEVEL_RANK.get(str(level).lower().replace(" ", "_"))


def _level_words(level: str | None, *, absent: str) -> str:
    """``notably_high`` is a band identifier; the page says ``notably high``."""
    return str(level).replace("_", " ") if level else absent


_PROFILE_LABELS: dict[str, str] = {}


def _profile_label(profile: str) -> str:
    """The reader-facing label from ``profiles/<id>.yaml``, falling back to
    the identifier with its underscores removed. ``ckd`` is an identifier;
    the page says ``Chronic kidney disease``."""
    if profile in _PROFILE_LABELS:
        return _PROFILE_LABELS[profile]
    label = profile.replace("_", " ")
    path = Path(__file__).resolve().parent.parent / "profiles" / f"{profile}.yaml"
    try:
        head = yaml.safe_load(path.read_text()) or {}
        raw = str(head.get("label") or "").strip()
        if raw:
            # "Chronic kidney disease — gut pattern" -> "Chronic kidney disease"
            label = raw.split(" \u2014 ")[0].split(" - ")[0].strip()
    except (OSError, yaml.YAMLError):
        pass
    _PROFILE_LABELS[profile] = label
    return label


def materialize_triggers(
    *,
    sample: str,
    panel_levels: Mapping[str, str | None],
    group_levels: Mapping[str, str | None],
    profile_levels: Mapping[str, str | None],
    profile_abstained: Iterable[str] = (),
    taxa_buckets: Mapping[str, str] = (),
    context: Mapping[str, Any] | None = None,
    qc_qualified: bool = True,
    index_levels: Mapping[str, str | None] | None = None,
) -> list[TriggerRecord]:
    """Step 1–2 of §7.7: typed triggers from QC-qualified evidence only.

    Levels are the seven-band percentile labels (``notably_low`` … ``notably_high``).
    Anything but the microbial namespaces comes from the subject context
    (clinician-confirmed conditions, symptoms, external labs).

    ``index_levels`` carries the v4.2 skin-condition families, banded from
    their 0–100 directional pattern index rather than from a percentile. They
    materialise as ``research_profile_resemblance`` triggers under their own
    namespace so a card can never mistake the index for a percentile."""
    out: list[TriggerRecord] = []
    if qc_qualified:
        for panel, level in panel_levels.items():
            rank = _rank(level)
            direction = "high" if rank is not None and rank > 0 else "low" if rank is not None and rank < 0 else "any"
            out.append(TriggerRecord(
                trigger_id=f"TRIGGER_{sample}_PANEL_{panel.upper()}", trigger_type="functional_capacity_finding",
                target=panel, direction=direction, source_record_ref=f"panel:{panel}",
                confirmation_status="profile_only", level=level, level_rank=rank,
                microbial_context={"body_site": "stool", "namespace": "gene_capacity_rpoB_normalised", "direction": direction},
                display=f"{panel.replace('_', ' ')} gene capacity: {_level_words(level, absent='no reference position')}",
            ))
        for group, level in group_levels.items():
            rank = _rank(level)
            direction = "high" if rank is not None and rank > 0 else "low" if rank is not None and rank < 0 else "any"
            out.append(TriggerRecord(
                trigger_id=f"TRIGGER_{sample}_GROUP_{group.upper()}", trigger_type="ecological_finding",
                target=group, direction=direction, source_record_ref=f"group:{group}",
                confirmation_status="profile_only", level=level, level_rank=rank,
                microbial_context={"body_site": "stool", "namespace": "MetaPhlAn3_species_relative", "direction": direction},
                display=f"{group.replace('_', ' ')} relative abundance: {_level_words(level, absent='no reference position')}",
            ))
        abstained = set(profile_abstained)
        for profile, level in profile_levels.items():
            if profile in abstained:
                continue
            rank = _rank(level)
            direction = "high" if rank is not None and rank > 0 else "low" if rank is not None and rank < 0 else "any"
            out.append(TriggerRecord(
                trigger_id=f"TRIGGER_{sample}_PROFILE_{profile.upper()}", trigger_type="research_profile_resemblance",
                target=profile, direction=direction, source_record_ref=f"profile:{profile}",
                confirmation_status="profile_only", level=level, level_rank=rank,
                microbial_context={"body_site": "stool", "namespace": "profile_similarity_percentile", "direction": direction},
                display=f"{_profile_label(profile)} pattern: {_level_words(level, absent='not scored')}",
            ))
        for family, level in dict(index_levels or {}).items():
            rank = _rank(level)
            direction = "high" if rank is not None and rank > 0 else "low" if rank is not None and rank < 0 else "any"
            out.append(TriggerRecord(
                trigger_id=f"TRIGGER_{sample}_INDEX_{family.upper()}", trigger_type="research_profile_resemblance",
                target=family, direction=direction, source_record_ref=f"skin_family:{family}",
                confirmation_status="profile_only", level=level, level_rank=rank,
                microbial_context={"body_site": "stool", "namespace": "directional_pattern_index_0_100", "direction": direction},
                display=f"{family.replace('_', ' ')} stool pattern: {_level_words(level, absent='not scored')}",
            ))
        for species, bucket in dict(taxa_buckets).items():
            direction = (
                "high" if bucket in ("high", "unexpected_present", "concern")
                else "low" if bucket in ("low", "absent_expected")
                else "present"
            )
            out.append(TriggerRecord(
                trigger_id=f"TRIGGER_{sample}_TAXON_{species.upper()}", trigger_type="exact_microbiome_feature",
                target=species, direction=direction,
                source_record_ref=f"taxon:{species}", confirmation_status="profile_only",
                level=bucket, level_rank=None,
                microbial_context={"body_site": "stool", "namespace": "MetaPhlAn3_species_relative", "direction": bucket},
                display=f"{species.replace('_', ' ')}: {bucket.replace('_', ' ')}",
            ))
    ctx = dict(context or {}).get("context", {}) if context else {}
    for cond in ctx.get("conditions", []) or []:
        out.append(TriggerRecord(
            trigger_id=f"TRIGGER_{sample}_CONDITION_{str(cond).upper()}", trigger_type="clinician_confirmed_condition",
            target=str(cond), direction="present", source_record_ref="manifest:context.conditions",
            confirmation_status="verified", display=f"clinician-confirmed {cond}",
        ))
    for cond in ctx.get("self_reported_conditions", []) or []:
        out.append(TriggerRecord(
            trigger_id=f"TRIGGER_{sample}_SELFREPORTED_{str(cond).upper()}", trigger_type="clinician_confirmed_condition",
            target=str(cond), direction="present", source_record_ref="manifest:context.self_reported_conditions",
            confirmation_status="self_reported", display=f"self-reported {cond}",
        ))
    for sym in ctx.get("symptoms", []) or []:
        out.append(TriggerRecord(
            trigger_id=f"TRIGGER_{sample}_SYMPTOM_{str(sym).upper()}", trigger_type="symptom_phenotype",
            target=str(sym), direction="present", source_record_ref="manifest:context.symptoms",
            confirmation_status="self_reported", display=f"reported {sym}",
        ))
    for lab in ctx.get("external_labs", []) or []:
        name = lab.get("name") if isinstance(lab, Mapping) else str(lab)
        out.append(TriggerRecord(
            trigger_id=f"TRIGGER_{sample}_LAB_{str(name).upper()}", trigger_type="external_lab_abnormality",
            target=str(name), direction=str(lab.get("direction", "present")) if isinstance(lab, Mapping) else "present",
            source_record_ref="manifest:context.external_labs", confirmation_status="verified",
            display=f"external lab {name}",
        ))
    return out


# --------------------------------------------------------------------------- #
# applicability + summary
# --------------------------------------------------------------------------- #


@dataclass(slots=True)
class Applicability:
    target_match: str = "none"
    population_match: str = "unknown"
    age_match: str = "unknown"
    sex_match: str = "unknown"
    disease_confirmation: str = "absent"
    medication_context_match: str = "unknown"
    assay_match: str = "not_applicable"
    endpoint_relevance: str = "mechanistic"
    protocol_identity: str = "class_only"
    known_dimension_coverage: float = 0.0

    def to_json(self) -> dict[str, Any]:
        return {
            "target_match": self.target_match, "population_match": self.population_match,
            "age_match": self.age_match, "sex_match": self.sex_match,
            "disease_confirmation": self.disease_confirmation,
            "medication_context_match": self.medication_context_match, "assay_match": self.assay_match,
            "endpoint_relevance": self.endpoint_relevance, "protocol_identity": self.protocol_identity,
            "known_dimension_coverage": round(self.known_dimension_coverage, 2),
        }


@dataclass(slots=True)
class EvidenceSummary:
    summary_id: str
    action_mapping_id: str
    title: str
    render: str
    trigger_ids: list[str]
    trigger_displays: list[str]
    intervention_id: str | None
    intervention_class: str | None
    intervention_display: str | None
    protocol_ref: str | None
    studied_protocol_text: str | None
    population_text: str | None
    supporting_evidence_lane: str
    strongest_study_design: str | None
    guideline_position: str
    outcome_relevance: str
    replication: str
    against_evidence: list[str]
    applicability: Applicability
    safety: SafetyVerdict
    display_policy: str
    action_status: str
    evidence_summary: dict[str, Any]
    eligibility_explanation: list[str]
    context_note: str
    never_say: list[str]
    follow_up_route: str | None
    fmt_status: str | None
    supporting: list[dict[str, Any]]
    against: list[dict[str, Any]]
    sources: list[dict[str, str]]
    rejections: list[str]
    participant_paragraphs: list[str]
    dose_shown: bool
    not_an_effect_probability: bool = True
    not_a_personalized_prescription: bool = True

    def to_json(self) -> dict[str, Any]:
        return {
            "summary_id": self.summary_id, "action_mapping_id": self.action_mapping_id, "title": self.title,
            "render": self.render, "trigger_ids": self.trigger_ids, "trigger_displays": self.trigger_displays,
            "intervention_id": self.intervention_id, "intervention_class": self.intervention_class,
            "intervention_display": self.intervention_display, "protocol_ref": self.protocol_ref,
            "studied_protocol_text": self.studied_protocol_text, "population_text": self.population_text,
            "supporting_evidence_lane": self.supporting_evidence_lane,
            "strongest_study_design": self.strongest_study_design, "guideline_position": self.guideline_position,
            "outcome_relevance": self.outcome_relevance, "replication": self.replication,
            "against_evidence": self.against_evidence, "applicability": self.applicability.to_json(),
            "known_safety_signal": self.safety.known_safety_signal, "safety": self.safety.to_json(),
            "display_policy": self.display_policy, "action_status": self.action_status,
            "evidence_summary": self.evidence_summary, "eligibility_explanation": self.eligibility_explanation,
            "context_note": self.context_note, "never_say": self.never_say, "follow_up_route": self.follow_up_route,
            "fmt_status": self.fmt_status, "supporting": self.supporting, "against": self.against,
            "sources": self.sources, "rejections": self.rejections,
            "participant_paragraphs": self.participant_paragraphs, "dose_shown": self.dose_shown,
            "not_an_effect_probability": True, "not_a_personalized_prescription": True,
        }


_DESIGN_RANK: Final = {
    "guideline": 0, "regulatory_label": 0, "meta_analysis": 1, "systematic_review": 1, "randomized_trial": 2,
    "nonrandomized_study": 3, "observational_study": 4, "case_report": 5, "protocol": 6, "preprint": 6,
    "consensus_statement": 1, "regulatory_safety_communication": 0, "reference_fact_sheet": 1,
}


def _population_text(protocol: Protocol | None) -> str | None:
    if protocol is None:
        return None
    pop = protocol.population
    bits = []
    if pop.get("confirmed_condition"):
        bits.append(f"people with clinically confirmed {pop['confirmed_condition']}")
    if pop.get("age_range_years"):
        lo, hi = pop["age_range_years"]
        bits.append(f"ages {lo}–{hi}")
    if pop.get("sex"):
        bits.append(str(pop["sex"]))
    if pop.get("geography"):
        bits.append(f"in {pop['geography']}")
    if pop.get("n"):
        bits.append(f"n = {pop['n']}")
    return ", ".join(bits) if bits else None


def _applicability(
    mapping: ActionMapping, protocol: Protocol | None, intervention: Intervention | None,
    triggers: Sequence[TriggerRecord], context: Mapping[str, Any], supporting: Sequence[Assertion],
) -> tuple[Applicability, list[str]]:
    app = Applicability()
    notes: list[str] = []
    subject = context.get("subject", {}) if context else {}
    ctx = context.get("context", {}) if context else {}
    confirmed = {str(c).lower() for c in ctx.get("conditions", []) or []}
    self_reported = {str(c).lower() for c in ctx.get("self_reported_conditions", []) or []}

    # target match
    kinds = {t.trigger_type for t in triggers}
    if "clinician_confirmed_condition" in kinds and any(t.confirmation_status == "verified" for t in triggers):
        app.target_match = "exact"
    elif "exact_microbiome_feature" in kinds or "functional_capacity_finding" in kinds:
        app.target_match = "related"
    elif "research_profile_resemblance" in kinds or "ecological_finding" in kinds:
        app.target_match = "indirect"

    # disease confirmation
    required = [c.lower() for c in mapping.confirmation_rule_refs]
    if required:
        if any(c in confirmed for c in required):
            app.disease_confirmation = "confirmed"
        elif any(c in self_reported for c in required):
            app.disease_confirmation = "self_reported"
            notes.append(f"The studied condition ({', '.join(mapping.confirmation_rule_refs)}) is self-reported here, not clinician-confirmed.")
        else:
            app.disease_confirmation = "profile_only"
            notes.append(
                "The study required a clinical diagnosis of "
                + ", ".join(r.replace("_", " ") for r in mapping.confirmation_rule_refs) + "."
            )
            notes.append("This report provides microbiome resemblance or capacity only.")
            notes.append("Clinical eligibility is therefore unconfirmed.")
    else:
        app.disease_confirmation = "absent"

    known = 0
    total = 0
    # age
    total += 1
    age = subject.get("age_years")
    if protocol is not None and protocol.population.get("age_range_years") and age is not None:
        lo, hi = protocol.population["age_range_years"]
        app.age_match = "exact" if lo <= age <= hi else "outside"
        known += 1
        if app.age_match == "outside":
            notes.append(f"Studied ages were {lo}–{hi}; this subject is outside that range.")
    elif age is not None:
        app.age_match = "exact" if age >= 18 else "outside"
        known += 1
    # sex
    total += 1
    sex = subject.get("sex")
    if protocol is not None and protocol.population.get("sex"):
        if sex is None:
            app.sex_match = "unknown"
            notes.append(f"The study enrolled {protocol.population['sex']} participants only; sex is not on file here.")
        else:
            app.sex_match = "exact" if str(protocol.population["sex"]).lower().startswith(str(sex).lower()[:1]) else "outside"
            known += 1
            if app.sex_match == "outside":
                notes.append(f"The study enrolled {protocol.population['sex']} participants only.")
    else:
        app.sex_match = "not_required"
        known += 1
    # population
    total += 1
    if protocol is None:
        app.population_match = "unknown"
    elif app.disease_confirmation == "confirmed" and app.age_match == "exact" and app.sex_match in ("exact", "not_required"):
        app.population_match = "exact"
        known += 1
    elif app.age_match == "outside" or app.sex_match == "outside":
        app.population_match = "outside"
        known += 1
    elif app.disease_confirmation in ("profile_only", "absent") and protocol.population.get("confirmed_condition"):
        app.population_match = "outside" if app.disease_confirmation == "profile_only" else "partial"
        known += 1
    else:
        app.population_match = "partial"
        known += 1
    # medication context
    total += 1
    if "medications" in ctx:
        app.medication_context_match = "exact" if ctx.get("medications") is not None else "unknown"
        known += 1
    # assay
    total += 1
    app.assay_match = "native" if any(t.microbial_context for t in triggers) else "not_applicable"
    known += 1
    # endpoint relevance from the best supporting record
    total += 1
    classes = [a.outcome_class for a in supporting]
    if any(c in ("patient_clinical", "patient_reported", "validated_biomarker") for c in classes):
        app.endpoint_relevance = "clinical"
    elif "microbiome_surrogate" in classes:
        app.endpoint_relevance = "surrogate"
    else:
        app.endpoint_relevance = "mechanistic"
    known += 1
    # protocol identity
    total += 1
    if intervention is not None:
        app.protocol_identity = "exact" if intervention.exact_protocol_reproducibility == "complete" else "partial"
    else:
        app.protocol_identity = "class_only"
    known += 1
    total += 1  # disease confirmation dimension itself
    if app.disease_confirmation in ("confirmed", "self_reported"):
        known += 1
    app.known_dimension_coverage = known / total if total else 0.0
    return app, notes


def _lane_and_replication(supporting: Sequence[Assertion]) -> tuple[str, str, str | None]:
    if not supporting:
        return "none", "none", None
    best = min(supporting, key=lambda a: LANES.index(a.lane) if a.lane in LANES else 99)
    designs = [a.source.get("source_type") for a in supporting]
    strongest = min(designs, key=lambda d: _DESIGN_RANK.get(str(d), 9)) if designs else None
    directions = {a.effect_direction for a in supporting}
    rct_benefit = [a for a in supporting if a.source.get("source_type") == "randomized_trial" and a.effect_direction == "benefit"]
    if "benefit" in directions and ({"null", "harm", "mixed"} & directions):
        replication = "conflicting"
    elif len(rct_benefit) >= 2:
        replication = "replicated"
    elif supporting:
        replication = "single_study"
    else:
        replication = "none"
    return best.lane, replication, str(strongest) if strongest else None


def _against_set(against: Sequence[Assertion]) -> list[str]:
    kinds = {a.against_kind for a in against if a.against_kind}
    return [k for k in AGAINST_ORDER if k in kinds]


def _assertion_json(a: Assertion, protocol: Protocol | None) -> dict[str, Any]:
    return {
        "evidence_assertion_id": a.evidence_assertion_id, "lane": a.lane, "lane_meaning": LANE_MEANING.get(a.lane, ""),
        "against_kind": a.against_kind, "proposition": a.proposition,
        "source_type": a.source.get("source_type"), "publication_status": a.source.get("publication_status", "peer_reviewed"),
        "citation": a.citation, "url": a.url, "design": a.study.get("design"),
        "participants": a.study.get("participants_randomized") or a.study.get("participants"),
        "risk_of_bias": a.study.get("risk_of_bias", "not_assessed"),
        "funding_and_conflicts": a.study.get("funding_and_conflicts"),
        "comparator": a.pico.get("comparator"), "outcome_class": a.outcome_class,
        "outcome": a.pico.get("outcome", {}).get("name"), "timepoint_days": a.pico.get("outcome", {}).get("timepoint_days"),
        "effect_direction": a.effect_direction, "effect": a.pico.get("effect", {}).get("estimate"),
        "guideline_position": a.guideline_position, "summary": a.summary,
        "studied_protocol": None if protocol is None else protocol.dose_text,
    }


def generate(
    registry: Registry,
    triggers: Sequence[TriggerRecord],
    *,
    sample: str,
    context: Mapping[str, Any] | None,
    mode: str = "participant",
) -> list[EvidenceSummary]:
    """§7.7 steps 2–14 for one sample. Output is unranked (registry order)."""
    context = dict(context or {})
    subject = context.setdefault("subject", {})
    subject.setdefault("mode", mode)
    subject.setdefault("age_known", subject.get("age_years") is not None)
    if subject.get("age_years") is not None:
        subject.setdefault("is_minor", float(subject["age_years"]) < 18)
    ctx = context.setdefault("context", {})
    for key in ("medications", "conditions", "self_reported_conditions", "allergies", "symptoms", "external_labs"):
        if key not in ctx or ctx[key] is None:
            ctx[key] = []

    summaries: list[EvidenceSummary] = []
    counter = 0
    for mapping in registry.mappings:
        matched = [t for t in triggers if mapping.trigger_selector.matches(t)]
        if not matched:
            continue
        # §7.7 step 3: microbial triggers need exact body site + namespace
        rejections: list[str] = []
        micro = [t for t in matched if t.microbial_context]
        for t in micro:
            if t.microbial_context and t.microbial_context.get("body_site") != "stool":
                rejections.append(f"{t.trigger_id}: body site {t.microbial_context.get('body_site')} is not stool")
        matched = [t for t in matched if not any(r.startswith(t.trigger_id) for r in rejections)]
        if not matched:
            continue
        counter += 1
        protocol = registry.protocols.get(mapping.intervention_protocol_ref) if mapping.intervention_protocol_ref else None
        intervention = registry.interventions.get(protocol.intervention_id) if protocol else None
        supporting = [registry.assertions[r] for r in mapping.evidence_assertion_refs]
        against = [registry.assertions[r] for r in mapping.against_evidence_assertion_refs]
        lane, replication, strongest = _lane_and_replication(supporting)
        against_set = _against_set(against)
        guideline = "unavailable"
        for a in supporting + against:
            if a.guideline_position != "unavailable":
                guideline = a.guideline_position
                break
        app, notes = _applicability(mapping, protocol, intervention, matched, context, supporting)

        # base display/action from render + confirmation (steps 6, 9)
        render = mapping.render
        if render in ("not_actionable", "no_supported_targeted_intervention") or render == "inform_only" or render == "evidence_only":
            base_display, base_action = "participant_summary", "evidence_only"
        elif render in ("clinician_review", "guideline_route_after_confirmation"):
            base_display = "clinician_only"
            base_action = "discussable_after_confirmation" if app.disease_confirmation == "confirmed" else "evidence_only"
        else:
            base_display, base_action = "evidence_only", "evidence_only"
        if mapping.confirmation_rule_refs and app.disease_confirmation != "confirmed":
            base_action = "evidence_only"
        if intervention is not None and intervention.intervention_class in ("prescription_drug", "fmt_microbiota_product"):
            base_display = "clinician_only"
            if mode == "participant":
                base_display = "evidence_only"
        if app.age_match == "outside" and subject.get("age_years") is not None and float(subject["age_years"]) < 18:
            base_display, base_action = "suppressed", "suppressed"
            rejections.append("subject is a minor: adult-derived intervention content is suppressed (§8.7)")
        if subject.get("age_years") is None and mode == "participant" and intervention is not None:
            # unknown age fails closed for any live-microbe / supplement / drug content
            base_display = "evidence_only"
            base_action = "evidence_only"
            rejections.append("age not on file: content shown as evidence only (§8.7 unknown age fails closed)")

        # step 8: every matching safety rule
        rules = [registry.safety_rules[r] for r in mapping.safety_rule_refs]
        verdict = apply_rules(
            rules, intervention.intervention_class if intervention else "clinical_route", context,
            base_display=base_display, base_action=base_action,
        )
        display_policy, action_status = verdict.display_policy, verdict.action_status
        if mode == "participant" and display_policy == "clinician_only":
            display_policy = "evidence_only"

        # step 12: never a benefit score. participant prose is deterministic.
        dose_shown = bool(mapping.participant_claim_release_ref) and mode != "participant"
        if mode != "participant" and intervention is not None:
            dose_shown = intervention.intervention_class not in ("prescription_drug", "fmt_microbiota_product") or mode == "clinician"
        paragraphs = _participant_paragraphs(
            registry, mapping, render, intervention, protocol, supporting, against, lane, replication, app,
            verdict, display_policy, dose_shown, mode,
        )
        summaries.append(EvidenceSummary(
            summary_id=f"EVIDENCE_SUMMARY_{sample}_{counter:03d}", action_mapping_id=mapping.action_mapping_id,
            title=mapping.title, render=render, trigger_ids=[t.trigger_id for t in matched],
            trigger_displays=[t.display for t in matched],
            intervention_id=intervention.intervention_id if intervention else None,
            intervention_class=intervention.intervention_class if intervention else None,
            intervention_display=intervention.display_name if intervention else None,
            protocol_ref=protocol.protocol_id if protocol else None,
            studied_protocol_text=protocol.dose_text if protocol and dose_shown else (
                "studied protocol on file (not shown in participant mode)" if protocol else None
            ),
            population_text=_population_text(protocol), supporting_evidence_lane=lane,
            strongest_study_design=strongest, guideline_position=guideline,
            outcome_relevance=app.endpoint_relevance, replication=replication, against_evidence=against_set,
            applicability=app, safety=verdict, display_policy=display_policy, action_status=action_status,
            evidence_summary={
                "benefit_assertions": sum(1 for a in supporting if a.effect_direction == "benefit"),
                "null_assertions": sum(1 for a in supporting + against if a.effect_direction == "null"),
                "harm_assertions": sum(1 for a in supporting + against if a.effect_direction == "harm"),
                "conflicting": replication == "conflicting" or "conflicting" in against_set,
                "strongest_study_design": strongest,
            },
            eligibility_explanation=notes, context_note=mapping.context_note, never_say=list(mapping.never_say),
            follow_up_route=mapping.follow_up_route, fmt_status=mapping.fmt_status,
            supporting=[_assertion_json(a, registry.protocols.get(a.protocol_ref) if a.protocol_ref else None) for a in supporting],
            against=[_assertion_json(a, registry.protocols.get(a.protocol_ref) if a.protocol_ref else None) for a in against],
            sources=list(mapping.sources), rejections=rejections, participant_paragraphs=paragraphs, dose_shown=dose_shown,
        ))
    return summaries


def _participant_paragraphs(
    registry: Registry, mapping: ActionMapping, render: str, intervention: Intervention | None,
    protocol: Protocol | None, supporting: Sequence[Assertion], against: Sequence[Assertion],
    lane: str, replication: str, app: Applicability, verdict: SafetyVerdict, display_policy: str,
    dose_shown: bool, mode: str,  # noqa: ARG001 — mode reserved for clinician-only phrasing
) -> list[str]:
    """Deterministic prose from approved records only."""
    out: list[str] = []
    if render == "no_supported_targeted_intervention" or (render == "not_actionable" and not supporting):
        out.append(NO_TARGETED_SENTENCE.format(version=registry.version))
    if mapping.context_note:
        out.append(mapping.context_note)
    if display_policy == "suppressed":
        out.append("Intervention content for this finding is not shown in this report. " + participant_safety_sentence(verdict))
        return out
    if intervention is not None:
        cls = intervention.intervention_class.replace("_", " ")
        lane_text = LANE_MEANING.get(lane, "")
        head = f"Human research evidence on record: {intervention.display_name} ({cls}), lane {lane} — {lane_text}."
        out.append(head)
        for a in supporting:
            s = a.summary or ""
            out.append(f"{s} [{a.citation}]" if s else f"[{a.citation}]")
        if protocol is not None:
            pop = _population_text(protocol)
            if pop:
                out.append(f"Studied population: {pop}. The studied protocol is a source fact, not an instruction for you.")
            if dose_shown:
                out.append(f"Studied protocol (source-reported): {protocol.dose_text}.")
        if intervention.intervention_class == "prescription_drug":
            out.append(PRESCRIPTION_SENTENCE)
        if intervention.intervention_class == "fmt_microbiota_product":
            out.append(FMT_STATUS_SENTENCE)
        if intervention.exact_protocol_reproducibility != "complete":
            out.append("The exact product composition is incompletely reported in the source; it has not been filled in from retail listings.")
    for a in against:
        out.append(f"Evidence against or limiting: {a.summary} [{a.citation}]")
    if app.disease_confirmation == "profile_only" and mapping.confirmation_rule_refs:
        out.append(
            f"This evidence applies to people with clinically confirmed {', '.join(mapping.confirmation_rule_refs).replace('_', ' ')}. "
            "A microbiome resemblance or capacity reading does not establish that diagnosis."
        )
    if replication == "conflicting":
        out.append("The human evidence is conflicting: positive and null or harmful results are shown together and are not averaged.")
    if mapping.follow_up_route:
        out.append(f"Conventional route: {mapping.follow_up_route}")
    if mapping.fmt_status:
        out.append(f"FMT status for this condition: {mapping.fmt_status.replace('_', ' ')}. " + FMT_STATUS_SENTENCE)
    out.append(participant_safety_sentence(verdict))
    out.append("Nothing here is a treatment score, a probability of benefit, or a personalised prescription. Discuss any change with a clinician or registered dietitian.")
    return out


# --------------------------------------------------------------------------- #
# convenience for the pipeline
# --------------------------------------------------------------------------- #


def default_registry_dir() -> Path:
    return Path(__file__).resolve().parent.parent / "interventions"


def write_lock(registry: Registry, path: Path) -> None:
    path.write_text(json.dumps(registry.to_lock(), indent=2))
